name: Validate Branch Name

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Branch Name
        id: validate_branch
        run: |
          # استخراج اسم الفرع من GITHUB_REF
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"
          
          # التحقق من اسم الفرع باستخدام regex
          if [[ "$BRANCH_NAME" =~ ^(bugfix|hotfix|release)\/[A-Za-z0-9-]+-[0-9]+\/[A-Za-z0-9-]+$ || "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "develop" ]]; then
            echo "Branch name is valid"
            exit 0
          else
            echo "Invalid branch name"
            exit 1
          fi
