name: Validate Branch Name

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Branch Name
        run: |
          BRANCH_NAME="${GITHUB_REF##*/}"
          echo "Branch name: $BRANCH_NAME"
          if [[ ! "$BRANCH_NAME" =~ ^(bugfix|hotfix|release)\/[A-Za-z0-9-]+-[0-9]+\/[A-Za-z0-9-]+$ ]]; then
            echo "Error: Invalid branch name. It must follow the pattern: <branch-type>/<Ticket-Id>/<task-name>"
            echo "Allowed prefixes: bugfix/, hotfix/, release/"
            exit 1
          fi
