name: Validate Branch Name

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Validate Branch Name
        id: validate_branch
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          echo "Branch name: $BRANCH_NAME"

          if [[ "$BRANCH_NAME" =~ ^(fix|release|bugfix|feature|hotfix|)/[A-Za-z0-9-]+-[0-9]+/[A-Za-z0-9-]+$ || "$BRANCH_NAME" == "master" || "$BRANCH_NAME" == "develop" ]]; then
            echo "Branch name is valid: $BRANCH_NAME"
            exit 0
          else
            echo "Invalid branch name: $BRANCH_NAME"
            exit 1
          fi
