name: Branch Name Validation

on:
  pull_request:
    branches:
      - '*'  # applies to all branches on PR creation or updates

jobs:
  validate-branch-name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: get_branch
        run: |
          echo "Getting branch name for PR..."
          BRANCH_NAME=${GITHUB_HEAD_REF}
          echo "::set-output name=branch::$BRANCH_NAME"
        shell: bash

      - name: Validate Branch Name
        run: ./.github/scripts/validate-branch-name.sh ${{ steps.get_branch.outputs.branch }}
